name: "Check Environments"

on:
  workflow_dispatch

jobs:
  check-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environments
        id: check
        uses: subhamay-bhattacharyya-gha/check-environments-action/action.yaml@feature/SB-0001-initial-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Environment Status
        run: |
          echo "Environment status: ${{ steps.check.outputs.env_status }}"
