name: "Check Environments"

on:
  workflow_dispatch

jobs:
  check-envs:
    name: "Check Environments"
    runs-on: ubuntu-latest
    steps:
      - name: Check Environments
        id: check
        uses: subhamay-bhattacharyya-gha/check-environments-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Environment Status
        run: |
          echo "Environment status: ${{ steps.check.outputs.env_status }}"
