name: CloudFormation Build
run-name: Build run by ${{ github.actor }} on ${{ github.ref_name }}

on:
  workflow_dispatch:

# env:
#   AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
#   AWS_REGION: ${{ vars.AWS_REGION }}


jobs:
  ci-build:
    uses: subhamay-bhattacharyya-gha/cfn-ci-reusable-wf/.github/workflows/ci.yaml@main
    with:
      aws-role-arn: ${{ env.AWS_ROLE_ARN }}
      aws-region: ${{ env.AWS_REGION }}
      cfn-template-file: root-stack-template.yaml
      cfn-params-file: ./cfn/params/cfn-parameters.json
      snyk-token: ${{ secrets.SNYK_TOKEN }}
