name: CloudFormation Build
run-name: Build run by ${{ github.actor }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: "ci"
        type: choice
        options:
          - ci
          - devl
          - test
          - prod


jobs:
  build:
    name: CI
    uses: subhamay-bhattacharyya-gha/cfn-ci-reusable-wf/.github/workflows/ci.yaml@feature/SB-0001-initial-release
    with:
      cfn-template-file: root-stack-template.yaml
      cfn-params-file: ./cfn/params/cfn-parameters.json
      environment: ${{ inputs.environment }}
      # snyk-token: 
